Change achievements label
Sitecore/Sitecore-Migration-Game pull request #112
Opened 2023-11-14 14:38 UTC by jst-cyr

Updated the 'Achievements' box with a new Card display to make it show a bit better on backgrounds, and also updated the title to 'Product Recommendations' based on feedback from the marketing team.

2023-11-14 20:31 UTC, thomas-desmond requested changes
If we remove the commented section this should be good to go. I like using the <Card>, it helps the hexagons stand out a lot more.

2023-11-14 20:31 UTC, thomas-desmond commented on src/components/ui/HexagonCollection/HexagonCollection.tsx
> +        {/* <Text fontSize={['lg', '2xl']} fontWeight="bold" textAlign="center" mb={[2, 10]} variant={'achievements'}>
Can we remove this commented out seciton

2023-11-14 22:46 UTC, jst-cyr commented
> If we remove the commented section this should be good to go. I like using the , it helps the hexagons stand out a lot more.

Removed the commented section. Good catch!

2023-11-14 23:19 UTC, thomas-desmond approved these changes

2023-11-15 16:36 UTC, thomas-desmond commented
Looks even better with the UI changes

2023-11-15 18:06 UTC, jst-cyr commented
I agree it looks better so merging this now, but we need to address some contrast issues with the background images.

2023-11-15 18:06 UTC, merged